-- Schema initialization is managed by Flyway migrations in:
-- backend/src/main/resources/db/migration
--
-- This file is intentionally left as no-op to avoid conflicts between
-- Docker init scripts and Flyway.
