spring.application.name=sggwstudentmap
spring.profiles.active=local

# polaczenie z baza danych
spring.datasource.url=jdbc:postgresql://localhost:5432/sggw_student_map
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update 
# validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0

# jwt
spring.jwt.secret=GxvYxk7uXo2y6h3bN2GqV5r9cG4f8w1zKjPqRtYuW0E=
#2 godz
spring.jwt.access-token-expiration=7200 
#7 dni
spring.jwt.refresh-token-expiration=604800

# CORS (Angular frontend)
app.cors.allowed-origins=http://localhost:4200

# Auth cookie defaults (override in non-local profiles)
app.auth.refresh-cookie-secure=true
app.auth.refresh-cookie-same-site=Lax
