spring.application.name=sggwstudentmap

# polaczenie z baza danych
spring.datasource.url=jdbc:postgresql://localhost:5432/sggw_student_map
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway - wylaczone, schemat zarzadzany przez init.sql
spring.flyway.enabled=false